apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.81.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    dashboard.enabled: "true"
    dashboard.domain: "traefik.k3s.hughobrien.ie"
    dashboard.ingress.annotations.kubernetes\.io/ingress\.class: "traefik"
    dashboard.ingress.annotations.traefik\.ingress\.kubernetes\.io/redirect-entry-point: "https"
    dashboard.ingress.annotations.cert-manager\.io/cluster-issuer: "letsencrypt"
    dashboard.ingress.tls[0].hosts[0]: "traefik.k3s.hughobrien.ie"
    dashboard.ingress.tls[0].secretName: "traefik-cert"
