---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: longhorn-system
  name: longhorn-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: longhorn.k3s.hughobrien.ie
      http:
        paths:
          - path: /
            backend:
              serviceName: longhorn-frontend
              servicePort: 80
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"  # 48 hours in minutes
  fromBackup: ""
