---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prometheus
  name: prometheus
data:

  entrypoint.sh: |
    #!/bin/sh
    set -xeu
    k8s_config_url="https://raw.githubusercontent.com/prometheus/prometheus/master/documentation/examples/prometheus-kubernetes.yml"
    k8s_config_file=$(mktemp)
    local_config_file="/config/prometheus-partial.yml"
    final_config_file=$(mktemp)

    wget -O "$k8s_config_file" "$k8s_config_url"
    cat "$k8s_config_file" "$local_config_file" > "$final_config_file"

    /bin/prometheus \
    --config.file="$final_config_file" \
    --storage.tsdb.path=/data \
    --storage.tsdb.retention.size=1GB \
    --storage.tsdb.wal-compression

  prometheus-partial.yml: |
    - job_name: prometheus
      static_configs:
      - targets: ["localhost:9090"]
    - job_name: traefik
      static_configs:
      - targets: ["traefik-prometheus.kube-system:9100"]
    global:
      scrape_interval: 30s
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prometheus
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: prometheus.k3s.hughobrien.ie
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: prometheus
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  name: prometheus
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn2
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prometheus
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: prometheus
          image: prom/prometheus:v2.17.1
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1
          command:
            - /config/entrypoint.sh
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus
        - name: tmp
          emptyDir:
        - name: config
          configMap:
            name: prometheus
            defaultMode: 0500
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: prometheus
